added hw-14-1 or 16-1
kenu21/jv-online-shop pull request #2
Opened 2019-09-17 18:13 UTC by kenu21

2019-09-18 11:45 UTC, boroda4436 requested changes

2019-09-18 11:45 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/BucketControler.java
> +        List<Item> allOrdersForUser = bucketService.getAllItems(ID_VASYA);
@kenu21 Я так розумію що ID_VASYA - це id користувача. Проте в твоєму BucketService цей метод приймає bucketId а не userId
_List<Item> getAllItems(Long bucketId);_

2019-09-18 11:45 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +    private static final Long BUCKED_ID_OF_VASYA = 0L;
@kenu21 тобі не потрібн змінна BUCKED_ID_OF_VASYA. І пліз перейменуй VASYA_ID на USER_ID

2019-09-18 11:45 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +        bucketService.create(bucket);
@kenu21 краще прибери всі ці штуки і зроби окремий контроллер /injectData який буде відповідати за створення деяких тестових даних в нашій БД

2019-09-18 11:45 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/DeleteFromBucketController.java
> +    private static final Long BUCKED_ID_OF_VASYA = 0L;
```suggestion
    private static final Long   USER_ID = 0L;
```

2019-09-18 11:45 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +public class BuyController extends HttpServlet {
```suggestion
public class AddItemToBucketController extends HttpServlet {
```

2019-09-18 11:52 UTC, kenu21 commented on src/main/java/mate/academy/internetshop/controller/BucketControler.java
> +        List<Item> allOrdersForUser = bucketService.getAllItems(ID_VASYA);
Так, ти правий.

2019-09-18 11:58 UTC, kenu21 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +    private static final Long BUCKED_ID_OF_VASYA = 0L;
OK

2019-09-18 12:03 UTC, kenu21 commented on src/main/java/mate/academy/internetshop/controller/DeleteFromBucketController.java
> +    private static final Long BUCKED_ID_OF_VASYA = 0L;
OK

2019-09-18 12:05 UTC, kenu21 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +public class BuyController extends HttpServlet {
OK

2019-09-18 12:42 UTC, kenu21 commented on src/main/java/mate/academy/internetshop/controller/BuyController.java
> +        bucketService.create(bucket);
@boroda4436 готово.

2019-09-19 07:52 UTC, boroda4436 approved these changes
@kenu21 не забудь змерджити пул реквест і видалити цю гілку

2019-09-19 07:58 UTC, merged